name: Go CI

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print current directory
        run: pwd
      - name: Change directory
        run: cd ./go-app
      - name: Print current directory
        run: pwd
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: go mod tidy
      - name: Run linter
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - name: Run tests
        run: go test ./...
