name: Go CI

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - name: Install dependencies
        working-directory: ./go-app
        run: go mod tidy && go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run linter
        working-directory: ./go-app
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - name: Run tests
        working-directory: ./go-app  
        run: go test ./...
