name: Go-CI-Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  Go-CI-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/go-app
        run: go mod tidy && go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run linter
        working-directory: ${{ github.workspace }}/go-app
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - name: Run tests
        working-directory: ${{ github.workspace }}/go-app  
        run: go test ./...
      - name: Create Docker Image
        working-directory: ${{ github.workspace }}/go-app
        run: docker build -t shraiyaparashar31/inc_42/go-app .
      - name: Push Docker Image
        working-directory: ${{ github.workspace }}/go-app  
        run: docker push shraiyaparashar31/inc_42/go-app
