name: NextJS-CI-Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/nextjs-app
        run: npm install
      - name: Run linter
        working-directory: ${{ github.workspace }}/nextjs-app 
        run: npm run lint
      - name: Run prettier
        working-directory: ${{ github.workspace }}/nextjs-app 
        run: npm run prettier
      - name: Run tests
        working-directory: ${{ github.workspace }}/nextjs-app
        run: npm test
