name: Wordpress-CI-Pipeline

on:
  push:
    branches:
      - main
      - 'feature/test*'

jobs:
  Wordpress-CI-Pipeline:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Set up PHP
         uses: shivammathur/setup-php@v2
         with:
            php-version: '7.4'
       - name: Install dependencies
         working-directory: ${{ github.workspace }}/wordpress-app
         run: composer install
       - name: Run PHPCS
         working-directory: ${{ github.workspace }}/wordpress-app
         run: vendor/bin/phpcs --standard=WordPress .
       - name: Run tests
         working-directory: ${{ github.workspace }}/wordpress-app
         run: vendor/bin/phpunit
       - name: Login to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
       - name: Create Docker Image
         working-directory: ${{ github.workspace }}/wordpress-app
         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress-app .
       - name: Push Docker Image
         working-directory: ${{ github.workspace }}/wordpress-app  
         run: docker push ${{ secrets.DOCKER_USERNAME }}/wordpress-app
